import { useRef, useState } from 'react'
import './App.css'

const topics = ['What is Git & Git Setup', 'Branching Strategies', 'Git Alias & Git Amend', 'Remote Operations', 'Advanced Commands', 'Git Copilot Integration', 'Hosting Static Websites', 'Hosting React Apps on Pages']
const students = [
  { initials: 'AM', name: 'Nilam Nerkar', role: 'engineer' },
  { initials: 'JL', name: 'Vaibhav More', role: 'engineer' },
  { initials: 'RK', name: 'Swapnil Baviskar', role: 'engineer' },
  { initials: 'SN', name: 'Ankush Nankar', role: 'engineer' },
  { initials: 'SN', name: 'Manswi patil', role: 'engineer' },
]
const branches = [
  { id: 'main', label: 'main', note: 'Production-ready code', color: 'green' },
  { id: 'feature', label: 'feature/ui', note: 'Build a new idea', color: 'coral' },
  { id: 'hotfix', label: 'hotfix/login', note: 'Patch a live issue', color: 'gold' },
]

function App() {
  const dashboardRef = useRef(null)
  const [completed, setCompleted] = useState([0, 1, 2, 3])
  const [activeBranch, setActiveBranch] = useState('feature')
  const toggleTopic = (index) => setCompleted((current) => current.includes(index) ? current.filter((item) => item !== index) : [...current, index])
  const scrollToDashboard = () => dashboardRef.current?.scrollIntoView({ behavior: 'smooth' })

  return (
    <main>
      <nav className="topbar"><a className="brand" href="#top" aria-label="DevOps Course home"><span className="brand-mark">&gt;_</span> devops<span className="brand-dot">.</span></a><div className="nav-links"><a href="#overview">Overview</a><a href="#topics">Curriculum</a><a href="#workflow">Workflow</a></div><button className="nav-cta" type="button" onClick={scrollToDashboard}>View dashboard <span>↗</span></button></nav>
      <section className="hero-section" id="top"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> Cohort 04 · Live learning</p><h1>DevOps<br /><em>Course</em></h1><p className="hero-subtitle">Welcome to the page</p><p className="hero-description">A practical path from your first commit to shipping with confidence. Learn the tools, habits, and thinking behind modern delivery.</p><button className="primary-button" type="button" onClick={scrollToDashboard}>Explore Course Details <span>↓</span></button><p className="hero-note">Built for curious beginners <span>·</span> No prior DevOps experience needed</p></div><div className="hero-visual" aria-label="Decorative Git commit visualization"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="commit commit-a">a1f2</div><div className="commit commit-b">c84d</div><div className="commit commit-c">e90b</div><div className="terminal-card"><div className="terminal-head"><span /><span /><span /><small>git / course</small></div><div className="terminal-line"><b>$</b> git status</div><div className="terminal-line muted">On branch <strong>main</strong></div><div className="terminal-line success">✓ nothing to commit, working tree clean</div><div className="terminal-line"><b>$</b> git log --oneline</div><div className="terminal-line muted">e90b ship: your first app</div><div className="terminal-line muted">c84d feat: merge the future</div></div><div className="visual-label">commit<br /><strong>your way forward</strong></div></div></section>
      <section className="dashboard" id="overview" ref={dashboardRef}><div className="section-heading"><p className="eyebrow">01 / the big picture</p><h2>Your course dashboard</h2><p>Everything you need to build a reliable foundation, in one place.</p></div><div className="overview-grid"><article className="overview-card agenda-card"><div className="card-top"><span className="card-kicker">COURSE NAME</span><span className="status-pill">In progress</span></div><h3>DevOps Foundations</h3><p>Agenda · 6 weeks of focused, hands-on learning</p><div className="agenda-list"><div><span>01</span> Version control essentials</div><div><span>02</span> Collaboration workflows</div><div><span>03</span> Ship a live React app</div></div></article><article className="overview-card mentor-card"><div className="card-kicker">YOUR MENTOR</div><div className="mentor-profile"><div className="avatar mentor-avatar">MC</div><div><h3>Maya Chen</h3><p>Staff Platform Engineer</p></div></div><p className="bio">“I help teams turn complex delivery problems into simple, repeatable systems.”</p><button className="text-button" type="button">Meet Maya <span>↗</span></button></article><article className="overview-card students-card"><div className="card-top"><span className="card-kicker">YOUR COHORT</span><span className="student-count">24 enrolled</span></div><h3>Learning together</h3><div className="student-list">{students.map((student) => <div className="student" key={student.name}><div className="avatar">{student.initials}</div><div><strong>{student.name}</strong><span>{student.role}</span></div></div>)}</div><p className="more-students">+ 20 more in your cohort</p></article></div></section>
      <section className="topics-section" id="topics"><div className="section-heading topic-heading"><div><p className="eyebrow">02 / what you’ll learn</p><h2>Topic: Git &amp; Version Control</h2></div><div className="progress-summary"><strong>{completed.length}<span>/ 9</span></strong><div><span>topics covered</span><div className="progress-bar"><i style={{ width: `${(completed.length / topics.length) * 100}%` }} /></div></div></div></div><div className="topic-grid">{topics.map((topic, index) => <button className={`topic-item ${completed.includes(index) ? 'is-complete' : ''}`} type="button" key={topic} onClick={() => toggleTopic(index)}><span className="checkmark">{completed.includes(index) ? '✓' : ''}</span><span><small>0{index + 1}</small>{topic}</span><span className="topic-arrow">↗</span></button>)}</div></section>
      <section className="diagrams-section" id="workflow"><div className="section-heading"><p className="eyebrow">03 / see it in motion</p><h2>From idea to shipped</h2><p>Click a branch to see how small, deliberate changes become a dependable release.</p></div><div className="diagram-grid"><article className="diagram-card branch-card"><div className="diagram-title"><div><span className="card-kicker">BRANCHING VISUALIZED</span><h3>A living history</h3></div><span className="diagram-icon">⑂</span></div><div className="branch-diagram"><div className="branch-line main-line"><span className="branch-label">main</span><i /><i /><i /><i /><b /></div><div className="branch-line feature-line"><span className="branch-label">feature/ui</span><i /><i /><i /><b /></div><div className="branch-line hotfix-line"><span className="branch-label">hotfix/login</span><i /><i /><b /></div><div className="merge-line" /></div><div className="branch-tabs">{branches.map((branch) => <button type="button" className={activeBranch === branch.id ? `active ${branch.color}` : ''} key={branch.id} onClick={() => setActiveBranch(branch.id)}><span>{branch.label}</span>{activeBranch === branch.id && <small>{branch.note}</small>}</button>)}</div></article><article className="diagram-card workflow-card"><div className="diagram-title"><div><span className="card-kicker">THE CORE LOOP</span><h3>Your code’s journey</h3></div><span className="diagram-icon">→</span></div><div className="workflow"><div className="workflow-node"><span className="node-number">01</span><strong>Working<br />directory</strong><small>your changes</small></div><span className="flow-arrow">→</span><div className="workflow-node"><span className="node-number">02</span><strong>Staging<br />area</strong><small>git add</small></div><span className="flow-arrow">→</span><div className="workflow-node"><span className="node-number">03</span><strong>Local<br />repository</strong><small>git commit</small></div><span className="flow-arrow">→</span><div className="workflow-node remote"><span className="node-number">04</span><strong>Remote<br />repository</strong><small>git push</small></div></div></article></div></section>
      <footer><a className="brand" href="#top"><span className="brand-mark">&gt;_</span> devops<span className="brand-dot">.</span></a><span>Learn deliberately. Ship confidently.</span><span>© 2024 DevOps Course</span></footer>
    </main>
  )
}

export default App
